### ISSUE TITLE
Database Error: Sorry, Something went wrong with the database

### ISSUE THREAD

**Issue by alex809** [AdKats/BFAdminCP#262]
Hey Colon,
Can't get it to work.

https://pastebin.com/qijVHDCr

Last night i got as far as "whoops, something went wrong" and never got that fixed. Then eventually reuploaded it today clean and set the database settings again, Then was able to get as far as "error in exception handler" which then once i did CTRL + F5 i got Database Error: Sorry, Something went wrong with the database.

It's being miserable lol, PHP7, Has the extensions, database information correct, wiped the bfacp tables and tried a few times gaining the same result.

**Comment by Prophet731** [comment]
The application doesn't support PHP 7, only PHP 5.6 and maybe down to version 5.4.

**Comment by alex809** [comment]
Ah ok, thanks bud. 
Working on trying to get a separate PHP version setup for it. Hopefully this tool for VestaCP works lol.

On an unrelated note for ADKats do you know what's causing this? I'm assuming my MySQL version is too new as well but not totally sure.

[22:08:00 85] [AdKats] EXCEPTION-6900-D-GetPopulatingPlayers-AccessFetching19: [Error while fetching populating players][MySql.Data.MySqlClient.MySqlException: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dkclan_cp_procon.adkats_records_main.target_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
   at PRoConEvents.AdKats.SafeExecuteReader(MySqlCommand command)
   at PRoConEvents.AdKats.GetPopulatingPlayers(TimeSpan duration, Int32 minPopulations, Boolean thisServerOnly)]

[22:08:00 95] [AdKats] EXCEPTION-6900-D-GetTopPlayers-AccessFetching19: [Error while fetching top players][MySql.Data.MySqlClient.MySqlException: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dkclan_cp_procon.adkats_statistics.target_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
   at PRoConEvents.AdKats.SafeExecuteReader(MySqlCommand command)
   at PRoConEvents.AdKats.GetTopPlayers(TimeSpan duration, Int32 minTops)]

**Comment by alex809** [comment]
Also, Another issue. I finally got PHP/5.6.31 installed and i'm still receiving the "Whoops, looks like something went wrong." error message.

I figured it was because MySQL was only version 5.5.52-MariaDB so i upgraded it, It's now Ver 15.1 Distrib 10.1.25-MariaDB

It's not even running the install so there's no logs generated within the app for me to view and / or provide. I set the virtual host document root to the /public folder of the app so that the subdomain loads /public at sub.domain.tld as it states it should.

**Comment by Prophet731** [comment]
That sql error looks like some sort of restriction based on its setup.

**Comment by alex809** [comment]
Nope wasn't that, It was working great but i changed the database username & then it started throwing that exception error.

Eventually after googling found Colon posted it in the Procon forums as a Definer issue and that the triggers needed to be changed, I couldn't find the triggers but eventually i discovered a Triggers tab in PhpMyAdmin, Changed the old MySQL Username in the triggers to the correct username and haven't had an error since.

Was just a pain trying to find "Definer=" to discover the triggers are in their own tab in phpmyadmin xD

**Comment by Prophet731** [comment]
Ahh ok. I wrote my reply while at work and only skimmed the error in the post. Yeah that'll cause the problem. Glad it's fixed now.
